name: Simple POC workflow

on: 
  push:
    branches:
      - "main"

jobs:
  simple-job:
    env:
      ENABLED: ${{ secrets.CICD_PLATFORM == 'github' }}
    if: ${{ env.ENABLED }}
    name: Simple Job 
    runs-on: ubuntu-latest

    steps:
      - name: Simple Step 
        run: echo "Hello Github Action"
