name: Simple POC workflow

on: 
  push:
    branches:
      - "main"

jobs:
  simple-job:
    if: ${{ secrets.CICD_PLATFORM }} == github'
    name: Simple Job 
    runs-on: ubuntu-latest

    steps:
      - name: Simple Step 
        run: echo "Hello Github Action"
