name: Simple POC workflow

on: 
  push:
    branches:
      - "main"

env:
  CICD_PLATFORM: ${{ secrets.CICD_PLATFORM }}

jobs:
  simple-job:
    if: ${{ env.CICD_PLATFORM == 'github' }}
    name: Simple Job 
    runs-on: ubuntu-latest

    steps:
      - name: Simple Step 
        run: echo "Hello Github Action"
